server:
  port: ${SERVER_PORT:8080}

security:
  admin:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  jwt:
    issuer: ${JWT_ISSUER}
    access-token:
      secret: ${ACCESS_TOKEN_SECRET}
      expiration-time-millis: ${ACCESS_TOKEN_EXPIRATION_TIME_MILLIS:60000}
    refresh-token:
      secret: ${REFRESH_TOKEN_SECRET}
      expiration-time-millis: ${REFRESH_TOKEN_EXPIRATION_TIME_MILLIS:604800000}